apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pi-app-db-config
  labels:
     app: db-config-ui
     tier: frontend
spec:
  replicas: {{ .Values.scale}}
  selector:
    matchLabels:
      app: db-config-ui
      tier: frontend
  template:
    metadata:
      labels:
        app: db-config-ui
        tier: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image:  dbconfig-ui:latest
          imagePullPolicy: IfNotPresent
          poerts:
          - containerPort:7777
          
