apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pi-app-db-config
spec:
  replicas: {{ .Values.scale}}
  selector:
    matchLabels:
      app: pi-app-db-config
  template:
    metadata:
      labels:
        app: pi-app-db-config
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
          - name: "interface"
            value: {{ .Values.proxy.ipaddress }}
          
