apiVersion: v1
kind: Service
metadata:
   name: dbconfigUI-piapp-service
   labels:
     app: dbconfigUI-piapp-service
spec:
   type: NodePort
   ports:
     - port: 7777
       nodePort: 30080
       targetPort: 7777
   selector:
       app: db-config-ui
       tier: frontend
